### PR TITLE
Add another comments config example

### PR DESCRIPTION
**Pull request by dbrgn**
Much simpler than the function :)

### CODE REVIEW

**Comment by TrySound** [comment]
@dbrgn Not quite sure it's supported stuff.

**Comment by dbrgn** [comment]
It is.

**Comment by TrySound** [comment]
As far as I know it was only in cli and gulp uglify, not core which is used here.

**Comment by dbrgn** [comment]
It seemed to work when I last played around with it. And I just used the command line interface of rollup, nothing related to Gulp.

**Pull request merged**
