### PR TITLE
Use uglify-js as uglify-es got deprecated in favour of terser

### PR DESCRIPTION
**Pull request by Andarist**
This requires **major bump**

### CODE REVIEW

**Comment by TrySound** [comment]
You are fast! Thanks.
Could you tweak also documentation links?

**Comment by Andarist** [comment]
done

**Comment by TrySound** [comment]
I will merge this when guys will solve the problem with Vasiliy Anonymov. Ping me if I will forget.

**Comment by Andarist** [comment]
I'm not aware of the problem with Vasiliy, so I'm not sure where to track this.

**Comment by TrySound** [comment]
He is squatter and has an access to terser on npm.
https://github.com/fabiosantoscode/terser/issues/2

**Comment by Andarist** [comment]
Hm, it seems `terser` is already published correctly.

**Comment by TrySound** [comment]
Yep, it's published but squatter has on access to terser and may broke it eventually.

**Pull request merged**
